### ISSUE TITLE
can't see my entities

### ISSUE THREAD

**Issue by jquievreux** [qcasey/ulauncher-homeassistant#6]
Hello, 

First of all thank you for this extension, I can't get it to work, though. I have configured it with my instance address and the key. But when I type in ha, it doesn't work. Or ha forecast. Ulauncher shows me loading and doesn't move.

Is there any way to get debugging information?

**Comment by qcasey** [comment]
Hi, could you double check that the URL is correct? To debug I'd do either of these:

1. Test with curl, using your API token and HA url:

```curl -v -H "Authorization: Bearer API_TOKEN_HERE" http://192.168.1.8:8123/api/states```

2. Quit and re-run ulauncher in the terminal, which may give you error logs if there's something weird going on.

Let me know if either of those shed any light!

**Comment by jquievreux** [comment]
I had not put in the url: https:// ... My bad

**Comment by qcasey** [comment]
No problem! It should account for that, I'll make the url less strict in the future.
